sources:
- archive: async-io-1.34.0.gem
  archive_sha512sum: 513bf5f97e2653ee46395c3f67d3a092ed94dedfb74183cde2479d9fb7cd21ff1ca22939ff4e406ef7845ad301c14e251b61c6ec3cc27c81b7dd9bb387115276
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Async::IO provides builds on async and provides asynchronous
        wrappers for IO, Socket, and related classes. '
      home_page: https://rubygems.org/gems/async-io/versions/1.34.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides support for asynchonous TCP, UDP, UNIX and SSL sockets.
      supplier: 'Organization: Broadcom, Inc.'
