sources:
- archive: concurrent-ruby-1.1.10.gem
  archive_sha512sum: ed01d65d79e6ed2987321f4665cb5f7c3fcd701029a33e68da0feb0cd6cb2682cef619566a3bd0996db207becb0425d77967b66ee66d775a489b1317e78807ab
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Modern concurrency tools including agents, futures, promises,
        thread pools, actors, supervisors, and more. Inspired by Erlang, Clojure,
        Go, JavaScript, actors, and classic concurrency patterns. '
      home_page: https://rubygems.org/gems/concurrent-ruby/versions/1.1.10
      license_concluded: MIT AND CC0-1.0
      license_declared: MIT AND CC0-1.0
      short_summary: Modern concurrency tools for Rails framework.
      supplier: 'Organization: Broadcom, Inc.'
