sources:
- archive: recursive-open-struct-1.1.3.gem
  archive_sha512sum: f092c87a321a36eef2fff947383126f1da5865ab557c6cc359f91b1fe7e265d1cf7fa476d88ce5d2947bbfa63c8c956ac9a9487f249ef04977c94af04b8af8e3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'RecursiveOpenStruct is a subclass of OpenStruct. It differs
        from OpenStruct in that it allows nested hashes to be treated in a recursive
        fashion. '
      home_page: https://rubygems.org/gems/recursive-open-struct/versions/1.1.3
      license_concluded: MIT
      license_declared: MIT
      short_summary: A subclass of OpenStruct that allows nested hashes to be treated
        in a recursive fashion
      supplier: 'Organization: Broadcom, Inc.'
