sources:
- archive: backports-3.23.0.gem
  archive_sha512sum: b6d721a2925a932e451437938e01c6e3f4ac08bafac975063963f7866e17015abfeb6862face89cbd08caf479db75eb085f540263ba251a87c6acc7611ba6d40
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Essential backports that enable many of the nice features
        of Ruby 1.8.7 up to 2.1.0 for earlier versions. '
      home_page: http://github.com/marcandre/backports
      license_concluded: MIT
      license_declared: MIT
      short_summary: Backports of Ruby features for older Ruby
      supplier: 'Organization: Broadcom, Inc.'
