sources:
- archive: fluent-plugin-kubernetes_metadata_filter-3.4.0.gem
  archive_sha512sum: 6383590639aab9a81aa87a191dcd5b7058e360dcf0ee7744e1a91b36e1c8b92f82a2f7de731883e208bb8e49d2dcc45285a714341e3fc226f1dfe4a8916c8bbf
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The Kubernetes metadata plugin filter enriches container
        log records with pod and namespace metadata. This plugin derives basic metadata
        about the container that emitted a given log record using the source of the
        log record. Records from journald provide metadata about the container environment
        as named fields. Records from JSON files encode metadata about the container
        in the file name. The initial metadata derived from the source is used to
        lookup additional metadata about the container''s associated pod and namespace
        (e.g. UUIDs, labels, annotations) when the kubernetes_url is configured. If
        the plugin cannot authoritatively determine the namespace of the container
        emitting a log record, it will use an ''orphan'' namespace ID in the metadata.
        This behaviors supports multi-tenant systems that rely on the authenticity
        of the namespace for proper log isolation. '
      home_page: https://rubygems.org/gems/fluent-plugin-kubernetes_metadata_filter/versions/3.4.0
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Fluentd Filter plugin to add Kubernetes metadata.
      supplier: 'Organization: Broadcom, Inc.'
