sources:
- archive: cool.io-1.7.1.gem
  archive_sha512sum: 9ab3e6ddd1689b2825f9bd82714b4ef5ac921dc4b2f84786971c3ec448577613cee73084c99090382878b0da43c9228cb2fd3a8627dc8f62ceeeff274dbdc929
  skip_validation: true
  spdx:
    package:
      detailed_description: 'a high performance event framework for Ruby which uses
        the libev C library '
      home_page: https://rubygems.org/gems/cool.io/versions/1.7.1
      license_concluded: MIT AND (BSD-2-Clause OR GPL-2.0-or-later)
      license_declared: MIT AND (BSD-2-Clause OR GPL-2.0-or-later)
      short_summary: a high performance event framework for Ruby which uses the libev
        C library
      supplier: 'Organization: Broadcom, Inc.'
