sources:
- archive: aws-eventstream-1.2.0.gem
  archive_sha512sum: d7d8a318523b1d4c4d950861f8fb4fb6b65a76b8df2bd788ca1d81d40f7a1d1fd91ad9db106892b508d348fd7f8678aa387b43ac390bcd75f8fb03d081c3e60b
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Amazon Web Services event stream library. Decodes and
        encodes binary stream under `vnd.amazon.event-stream` content-type '
      home_page: https://rubygems.org/gems/aws-eventstream/versions/1.2.0
      license_concluded: Apache-2.0
      license_declared: Apache-2.0
      short_summary: Amazon Web Services event stream library.
      supplier: 'Organization: Broadcom, Inc.'
