sources:
- archive: fluent-plugin-vmware-loginsight-1.3.0.gem
  archive_sha512sum: e076332f0905e73614186e218f86e8df592d9b0aad2c4f09cf825c3c1383ad402b64580642e89ed86a95d76cbfabe8cec6236ed57a2823bbae986ee51e050fa3
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Fluent output plugin to forward logs to VMware Log Insight. '
      home_page: https://rubygems.org/gems/fluent-plugin-vmware-loginsight/versions/1.3.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: Fluent output plugin to forward logs to VMware Log Insight.
      supplier: 'Organization: Broadcom, Inc.'
