sources:
- archive: mini_portile-0.6.2.gem
  archive_sha512sum: fd6ce49b5db291e8216f001e4a3bd14d69a920d6d457de7566f7526abf616dad3ec86d4951ab4b881ffd185b4d4e02e64eb2ae494cd9a1275e342b78afa4e2bc
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Simplistic port-like solution for developers. It provides
        a standard and simplified way to compile against dependency libraries without
        messing up your system. '
      home_page: https://rubygems.org/gems/mini_portile/
      license_concluded: MIT
      license_declared: MIT
      short_summary: Simplistic port-like solution for developers
      supplier: 'Organization: Broadcom, Inc.'
