sources:
- archive: http-parser-1.2.3.gem
  archive_sha512sum: 03c34c3e8174d9010440483af34800b74a7bbddd5daa63607e6aa2254d9c91cf36d90854ea65827b32680432de278aeeb7b8878f788f124c150f163409fa5107
  skip_validation: true
  spdx:
    package:
      detailed_description: 'An easy-to-use client library for making requests from
        Ruby. It uses a simple method chaining system for building requests, similar
        to Python''s Requests. '
      home_page: https://rubygems.org/gems/http-parser
      license_concluded: MIT
      license_declared: MIT
      short_summary: An easy-to-use client library for making requests from Ruby.
      supplier: 'Organization: Broadcom, Inc.'
