sources:
- archive: unf_ext-0.0.8.2.gem
  archive_sha512sum: c9d3e54c96a525031d3b2fe349b5ffa1d03e3f28f74c3a2715af299e5274c7514526d07be5d7244a2cf9561c11e170b15c75d34c5e2a7143cef1ee25d32d2137
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Unicode Normalization Form support library for CRuby. '
      home_page: https://rubygems.org/gems/unf_ext/versions/0.0.8.2
      license_concluded: MIT
      license_declared: MIT
      short_summary: Unicode Normalization Form support library for CRuby.
      supplier: 'Organization: Broadcom, Inc.'
