sources:
- archive: oj-3.13.21.gem
  archive_sha512sum: 9a1429cf6197a1ab7b679185dc48570d17bc387e1d62bf0758b36797976ba60c9fca0680af3b64c0b4e1c8e873fe4a892018f571644650fa32bd67a4d03a0c05
  skip_validation: true
  spdx:
    package:
      detailed_description: 'The fastest JSON parser and object serializer. '
      home_page: https://rubygems.org/gems/oj/versions/3.13.21
      license_concluded: MIT
      license_declared: MIT
      short_summary: The fastest JSON parser and object serializer.
      supplier: 'Organization: Broadcom, Inc.'
