sources:
- archive: trollop-2.9.10.gem
  archive_sha512sum: 21a0db09d480353ff846a1311b118e0b0db4ca13a559dd1749c1478eff7080dd04e5308dbf1807215eadb68e276c991970b23357e9a3497acb9f705f7f77253c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Commandline option parser for Ruby '
      home_page: https://rubygems.org/gems/trollop
      license_concluded: MIT
      license_declared: MIT
      short_summary: Commandline option parser for Ruby
      supplier: 'Organization: Broadcom, Inc.'
