sources:
- archive: http-form_data-2.3.0.gem
  archive_sha512sum: c070126d18a66bd505005d7dae4ece6c751e52593806daf618bbb437b7f9296a5f18aac2e317b3526c9b34adc2f4d9fc7b7bab8cf2a8c8ca67fdc5940969ff21
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Utility-belt to build form data request bodies. Provides
        support for application/x-www-form-urlencoded and multipart/form-data types. '
      home_page: https://rubygems.org/gems/http-form_data/versions/2.3.0
      license_concluded: MIT
      license_declared: MIT
      short_summary: Utility-belt to build form data request bodies. Provides support
        for application/x-www-form-urlencoded and multipart/form-data types.
      supplier: 'Organization: Broadcom, Inc.'
