sources:
- archive: enchant-vendor-2.5.0.tar.gz
  archive_sha512sum: 0e5ecc1fa158b3778425139a86e603ed187b089b7cab2832715f205fb776b43e80536720a780ca6b73d05771aaee6364141e632d989206c40d09e8bb6c13119c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Enchant aims to provide a simple but comprehensive abstraction
        for dealing with different spell checking libraries in a consistent way. '
      home_page: https://github.com/AbiWord/enchant/tree/v2.5.0
      license_concluded: GPL-2.0-only AND Apache-2.0 AND GPL-1.0-or-later WITH Autoconf-exception-generic
        AND LGPL-2.1-only AND CC-BY-ND-3.0 AND MPL-1.0 AND GPL-3.0-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND Zlib AND GFDL-1.3-only AND AGPL-3.0-only
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND SunPro AND FSFULLRWD
        AND MIT AND LGPL-2.0-or-later AND LGPL-3.0-only AND AGPL-3.0-or-later AND
        CC0-1.0 AND Artistic-2.0 AND BSD-4-Clause AND (LGPL-3.0-or-later AND GPL-2.0-or-later)
        AND FSFAP-no-warranty-disclaimer AND GPL-3.0-only AND LGPL-2.1-or-later AND
        GPL-3.0-or-later WITH Autoconf-exception-generic AND GPL-3.0-or-later WITH
        Texinfo-exception AND ISC AND FSFAP AND BSD-3-Clause AND LGPL-3.0-or-later
        AND (LGPL-3.0-or-later OR GPL-2.0-or-later) AND GFDL-1.1-or-later AND Unicode-3.0
        AND GPL-1.0-or-later AND FSFULLR AND GFDL-1.3-or-later AND X11 AND LGPL-2.0-only
        AND FSFUL AND GFDL-1.3-no-invariants-only AND MPL-2.0 AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND GFDL-1.3-invariants-only
      license_declared: GPL-2.0-only AND Apache-2.0 AND GPL-1.0-or-later WITH Autoconf-exception-generic
        AND LGPL-2.1-only AND CC-BY-ND-3.0 AND MPL-1.0 AND GPL-3.0-or-later AND GPL-2.0-or-later
        WITH Autoconf-exception-generic AND Zlib AND GFDL-1.3-only AND AGPL-3.0-only
        AND GPL-3.0-or-later WITH Autoconf-exception-generic-3.0 AND SunPro AND FSFULLRWD
        AND MIT AND LGPL-2.0-or-later AND LGPL-3.0-only AND AGPL-3.0-or-later AND
        CC0-1.0 AND Artistic-2.0 AND BSD-4-Clause AND (LGPL-3.0-or-later AND GPL-2.0-or-later)
        AND FSFAP-no-warranty-disclaimer AND GPL-3.0-only AND LGPL-2.1-or-later AND
        GPL-3.0-or-later WITH Autoconf-exception-generic AND GPL-3.0-or-later WITH
        Texinfo-exception AND ISC AND FSFAP AND BSD-3-Clause AND LGPL-3.0-or-later
        AND (LGPL-3.0-or-later OR GPL-2.0-or-later) AND GFDL-1.1-or-later AND Unicode-3.0
        AND GPL-1.0-or-later AND FSFULLR AND GFDL-1.3-or-later AND X11 AND LGPL-2.0-only
        AND FSFUL AND GFDL-1.3-no-invariants-only AND MPL-2.0 AND GPL-2.0-or-later
        AND GPL-2.0-or-later WITH Libtool-exception AND GFDL-1.3-invariants-only
      short_summary: A spellchecking library
      supplier: 'Organization: Broadcom, Inc.'
