sources:
- archive: http-cookie-1.0.5.gem
  archive_sha512sum: d530d64b5c2fc3757a6de03384fe768317e24a523d4a4215f5bcc6b5bca9e7b94eeaad1e52fbb67548396b7b2ca7c9d8b68ea7b99109e24770fcf34c950469ef
  skip_validation: true
  spdx:
    package:
      detailed_description: 'HTTP::Cookie is a Ruby library to handle HTTP Cookies
        based on RFC 6265. It has with security, standards compliance and compatibility
        in mind, to behave just the same as today''s major web browsers. It has builtin
        support for the legacy cookies.txt and the latest cookies.sqlite formats of
        Mozilla Firefox, and its modular API makes it easy to add support for a new
        backend store. '
      home_page: https://rubygems.org/gems/http-cookie/versions/1.0.5
      license_concluded: MIT
      license_declared: MIT
      short_summary: HTTP::Cookie is a Ruby library to handle HTTP Cookies based on
        RFC 6265.
      supplier: 'Organization: Broadcom, Inc.'
