sources:
- archive: mime-types-data-3.2022.0105.gem
  archive_sha512sum: 4b5998fb5d39ba89d4ee4f2f1fe20ec93a6b7214b28b77421dd9f7647b14c88342ba17f709f34640f65ce4c1bda08bd2be4aa35c7f99ea1ba2f9e21458540a00
  skip_validation: true
  spdx:
    package:
      detailed_description: 'mime-types-data provides a registry for information about
        MIME media type definitions. It can be used with the Ruby mime-types library
        or other software to determine defined filename extensions for MIME types,
        or to use filename extensions to look up the likely MIME type definitions. '
      home_page: https://rubygems.org/gems/mime-types-data/versions/3.2022.0105
      license_concluded: MIT
      license_declared: MIT
      short_summary: Provides a registry for information about MIME media type definitions.
      supplier: 'Organization: Broadcom, Inc.'
