sources:
- archive: zip-2.0.2.gem
  archive_sha512sum: 5a4c16173d52dc59206d414e88d4f218373d8d145b2996d0c7099036a57f30acb69f18131a550be4fb9973f1b6cf4de53b82d1d9e5da4e375e81a482399867b5
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Ruby library for reading and writing Zip files '
      home_page: https://rubygems.org/gems/zip
      license_concluded: BSD-2-Clause OR Ruby
      license_declared: BSD-2-Clause OR Ruby
      short_summary: Ruby library for reading and writing Zip files
      supplier: 'Organization: Broadcom, Inc.'
