sources:
- archive: mustache-1.1.1.gem
  archive_sha512sum: 91a18a374a0348317d0801d6784fedd0782d7a08f128d3ab7050e631b34e45cecd49c4b1e2a9e17204f70bf169c107a92a1e210532bd3faa98edf8b1b5e8e43c
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Mustache is a replacement for your views. Instead of
        views consisting of ERB or HAML with random helpers and arbitrary logic, your
        views are broken into two parts: a Ruby class and an HTML template '
      home_page: https://rubygems.org/gems/mustache/versions/1.1.1
      license_concluded: MIT
      license_declared: MIT
      short_summary: A framework-agnostic way to render logic-free views
      supplier: 'Organization: Broadcom, Inc.'
