sources:
- archive: timers-4.3.5.gem
  archive_sha512sum: 075b9c530b62e91ec4de995d1fc88667aac71372ef455343059294f075d57d6bcd52a36e182bd6b735852c9bfd8f0319d676ae377aaf060b857f5f3060b9e7c2
  skip_validation: true
  spdx:
    package:
      detailed_description: 'Schedule procs to run after a certain time, or at periodic
        intervals, using any API that accepts a timeout. '
      home_page: https://rubygems.org/gems/timers/versions/4.3.5
      license_concluded: MIT
      license_declared: MIT
      short_summary: Schedule procs to run after a certain time, or at periodic intervals,
        using any API that accepts a timeout.
      supplier: 'Organization: Broadcom, Inc.'
